# @package _group_

cnn_decoder: T2-huge
embedding_kernel_type: rbf
embedding_kernel_length_scale: 7.0
embedding_kernel_sigma_var: 1.0
embedding_kernel_learnable: True
normalise_embedding: True
output_kernel_type: rbf
output_kernel_length_scale: 5.0
output_kernel_sigma_var: 1.0
output_kernel_learnable: True
normalise_output: True
covariance_activation: diagonal_quadratic
covariance_activation_parameters: {}
grid_ranges: [-10, 10]
n_axes: 30
x_dim: 2
context_dim: 2
prediction_dim: 2
context_in_target: False
lr: 5e-4

name: ${model.cnn_decoder}