# @package _group_

cnn_decoder: D16-regular_huge
sigmoid_mean: True
embedding_kernel_type: rbf
embedding_kernel_length_scale: 0.5
embedding_kernel_sigma_var: 1.0
embedding_kernel_learnable: False
normalise_embedding: True
output_kernel_type: rbf
output_kernel_length_scale: 0.5
output_kernel_sigma_var: 1.0
output_kernel_learnable: False
normalise_output: True
min_cov: 0.01
covariance_activation: diagonal_softplus
covariance_activation_parameters: {}
x_dim: 2
context_dim: 1
prediction_dim: 1
context_in_target: False
padding_mode: zeros
lr: 3e-4

name: ${model.cnn_decoder}